name: Healthcare Stroke Dataset Preprocess

on:
  push:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          cd ./preprocessing
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run automate.py
        run: |
          cd ./preprocessing
          python automate_Bayu-Nugroho.py
